acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

blog:
    path: /blog/{page}
    defaults: { _controller: AcmeBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d+

blog_show:
    path: /blog/{slug}
    defaults: { _controller: AcmeBlogBundle:Blog:show }

